global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "api"
    metrics_path: /metrics
    static_configs:
      - targets: ["app:80"]

  - job_name: "keycloak"
    metrics_path: /metrics
    static_configs:
      - targets: ["keycloak:8080"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
